---
title: "Lecture 3"
subtitle: "Quantitative Political Science"
author: "Prof. Bisbee"
institute: "Vanderbilt University"
date: "Lecture Date: 2024/08/29\n Slides Updated: `r Sys.Date()`"
output:
  xaringan::moon_reader:
    # self_contained: true
    chakra: libs/remark-latest.min.js
    lib_dir: libs
    css:
      - default
      - css/lexis.css
      - css/lexis-fonts.css
    #seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"

---

```{css,echo = F}
.small .remark-code { /*Change made here*/
  font-size: 85% !important;
}
.tiny .remark-code { /*Change made here*/
  font-size: 50% !important;
}
```

```{r,include=F}
set.seed(123)
options(width=60)
knitr::opts_chunk$set(fig.align='center',fig.width=9,fig.height=5)
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
require(tidyverse)
```

# Agenda

1. Probability theory

2. Set theory

3. Combining to go from populations to samples

---

# Probability Theory: The Logic

--

- Familiar with moving from populations to samples

--

  - Given a 52 card deck with 13 spades, what is the probability of drawing a spade at random from a perfectly shuffled deck?
  
--
  
  - **Population**: 52 card deck with 13 spades
  
  - **Sample**: draw a card a random
  
--

  - 1/4: we know the distribution of spades in the population, and we are precise about sampling process
  
---

# Probability Theory; The Logic

- Run it in reverse!

--

- We know the sample

--

  - Central tendency ( $\bar{y}$ )
  
  - Dispersion ( $s^2$ )
  
--

- Make assumptions about sampling process to make **good** guesses about the population's central tendency ( $\mu$ ) and dispersion ( $\sigma^2$ )

--

- Learn the tools of the **population-to-sample** process to understand the **sample-to-population** process

---

# A Probabilistic Model for an Experiment

- **Experiments** describe the *process by which an observation is made*

--

- An **observation** is a quantity of interest:

--

  - The price of a stock
  
  - The number of subjects who choose "A" instead of "B"
  
  - The proportion of respondents who approve of Biden's job as president
  
--

- Experiments produce outcomes called **events**

---

# Example of an Experiment

- Election in a country with 101 voters; majority rule; everyone votes for either A or B

--

  - Possible **events**?

--

  a. Candidate A wins
  
  b. Candidate B wins
  
  c. Candidate A wins with 76 votes
  
  d. Candidate B wins with 56 votes
  
  e. Candidate A wins in a "landslide" ( $\geq 67$ votes)
  
  - Others?
  
--

- Note that a. can be decomposed into several other events

--

  a.1 Candidate A wins with 51 votes
  
  a.2 Candidate A wins with 52 votes
  
  a...
  
---

# Example of an Experiment

- Types of events

--

  - **Compound**: a., b., and e.
  
  - **Simple**: c. and d.
  
--

- **Set theory**

--

  - Associate a distinct point -- a **sample** point -- with each simple event
  
  - Refer to simple event $i$ as $E_i$
  
--

- **Sample space $S$**: set of all possible sample points

--

- How many in this example?

--

- $S = \{E_1, E_2, \dots E_{102}\}$

---

# Set Theory

- $S$ consists of countable (finite) number of sample points

--

  - **Discrete sample space**
  
  - Sample points are mutually exclusive
  
--

- Compound events are sets of sample points

--

  - "A wins by a landslide" occurs if one of $E_{68},\dots,E_{102}$ occurs
  
  - $A = \{E_{68},\dots,E_{102}\}$
  
--

- Thus an **event** is a collection of sample points

--

  - A subset of $S$
  
- *Aside on set theory notation*
  
