---
title: "Lecture 1"
subtitle: "Quantitative Political Science"
author: "Prof. Bisbee"
institute: "Vanderbilt University"
date: "Lecture Date: 2024/08/22\n Slides Updated: `r Sys.Date()`"
output:
  xaringan::moon_reader:
    # self_contained: true
    chakra: libs/remark-latest.min.js
    lib_dir: libs
    css:
      - default
      - css/lexis.css
      - css/lexis-fonts.css
    #seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"

---

```{css,echo = F}
.small .remark-code { /*Change made here*/
  font-size: 85% !important;
}
.tiny .remark-code { /*Change made here*/
  font-size: 50% !important;
}
```

```{r,include=F}
set.seed(123)
options(width=60)
knitr::opts_chunk$set(fig.align='center',fig.width=9,fig.height=5)
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
require(tidyverse)
```

# Agenda

1. Meet the instructor

2. Why are you here?

3. Variables 101

4. Data and summarizing data

5. Review syllabus and expectations

---

# Meet the instructor

- Education

--

  - PhD from NYU Politics in 2019

  - Postdocs at Princeton Niehaus & NYU CSMaP
  
--

- Published some things

--

  - Methods-ey: external validity [1](https://www.journals.uchicago.edu/doi/full/10.1086/691280?af=R), [2](https://www.cambridge.org/core/journals/american-political-science-review/article/testing-social-science-network-theories-with-online-network-data-an-evaluation-of-external-validity/4BF517F10F38DFB574FED4A3D805B613); measurement [3](https://www.cambridge.org/core/journals/american-political-science-review/article/barp-improving-mister-p-using-bayesian-additive-regression-trees/630866EB47F9366EDB3C22CFD951BB6F), [4](https://www.cambridge.org/core/journals/political-analysis/article/geographic-boundaries-and-local-economic-conditions-matter-for-views-of-the-economy/32C8C058B8E16CAD48374F95B2B1B3EF)

  - Substantive: economics & populism [1](https://www.tandfonline.com/doi/full/10.1080/13501763.2019.1678662); Covid-19 & U.S. politics [2](https://www.journals.uchicago.edu/doi/10.1086/716969),  [3](https://www.cambridge.org/core/journals/american-political-science-review/article/flight-to-safety-covidinduced-changes-in-the-intensity-of-status-quo-preference-and-voting-behavior/AE84D93BAF8B27284DD8F6A75DE5D18A); IPE [4](https://doi.org/10.1017/S0020818319000109); academic naval-gazing [5](https://www.cambridge.org/core/journals/perspectives-on-politics/article/abs/polisci-twitter-a-descriptive-analysis-of-how-political-scientists-use-twitter-in-2019/C8A193C3E939C1ABCD4600DFE8AEF79A?utm_source=hootsuite&utm_medium=twitter&utm_campaign=PPS_Dec20)

  - Popular press: [1](https://www.washingtonpost.com/news/monkey-cage/wp/2018/04/04/losing-jobs-to-free-trade-makes-americans-more-protectionist-and-nativist/), [2](https://www.washingtonpost.com/politics/2020/04/02/sanders-was-losing-biden-anyway-he-lost-more-areas-with-coronavirus-cases/?utm_medium=social&utm_source=twitter&utm_campaign=wp_monkeycage), [Podcasts](https://www.niskanencenter.org/did-chinese-trade-competition-increase-nativism-and-elect-trump/)
  
--

- Work

--

  - World Bank / IFC
  
  - MarketCast


---

# Why are you here?

--

- I.e., why are you getting a PhD in political science? 

--

  - You enjoy asking and answering questions about **politics**
  
--

  - What questions are you interested in?

---

# How I can help

--

- Quantitative analysis is one of many tools to answer your questions

--

  - Based on **numerical** measurements
  
  - Interested in developing and testing **generalizable** theories
  
  - Measurements and analyses that are easily **replicable** by others
  
--

- Contrast to other two dominant paradigms in political science research

--

  1. Qualitative analyses
  
  2. Formal modeling
  
--

- Never **ever** fall into the petty trap that quantitative is somehow "better"

--

  - “A foolish consistency is the hobgoblin of little minds, adored by little statesmen and philosophers and divines."
  
--

- You are here because you do not have a little mind
  
  


---

# Quantitative Analysis

- Political scientists work with quantitative data for three reasons:

--

  1. What can we say about the data **we have**?
  
--

  2. What can we say about the data **we don't have**?
  
--

  3. What can we say about the data **we'd expect to see**?
  
--

- Answering these questions requires three types of statistics

--

  1. Descriptive
  
--

  2. Inferential (from samples to populations)
  
--

  3. Prediction (from models to hypotheticals)
  
--

- All three of these approaches rely on **a test statistic**

--

  - A number that **summarizes data**

---

# Background

- Handout work

---

# Variables 101

- We study **units**

--

  - Phenomena about which we wish to make statements
  
--

  - AKA **cases**: people, counties, nations, dyads, etc.
  
--

- Units have **attributes**

--

  - Characteristics of a **unit** that distinguish it from other units
  
--

- **Variables** are *logical* groupings of *mutually exclusive* attributes

--

  - An important part of quantitative research is assigning a **value** to each attribute
  
--

  - The variable **GDP per capita** takes on the value **$2,256** for the unit **India**
  
  - The variable **year** takes on the value **first** for the unit **you**
  
--

- In quantitative analysis, we assign **scores** to each **value**

---

# Levels of measurement

- Variables can be measured at four levels

--

  1. **Nominal**: cannot be ordered in any logical way
  
  2. **Ordinal**: can be ordered, but no meaning to differences
  
  3. **Interval**: ordinal variables whose differences can be compared
  
  4. **Ratio**: zero is meaningful -- *nothing* of the quantity measured
  
--

- Mathematical operations can be conducted on these levels 

--

  1. **Nominal**: equality ( $=$ ) only (do these take on the same value or not?)
  
  2. **Ordinal**: equality, greater than ( $>$ ) or less than ( $<$ )
  
  3. **Interval**: addition ( $+$ ), subtraction ( $-$ ), averages ( $\frac{1}{n} \sum_i x_i$ )
  
  4. **Ratio**: multiplication ( $*$ ) and division ( $/$ )
  
---

# Tricky cases:

--

  - Celsius? Latitude and longitude? Binary variables?
  
---

# Data structures

- **Data table** (or **data frame**)

--

  - Rows are **units**
  
  - Columns are **variables**
  
  - Cells are **scores**
  
--

- **List**: Tree-like structure

--
  
  - Units are **outermost node**
  
  - Attributes are **child nodes**
  
  - Scores are **children of attributes**
  
--

- We will only use **data table** / **data frames** this semester

--

- But if you want to communicate with CS / engineers / data scientists, **lists** are their world!

---

# Logistics

- Syllabus review

--

- TA office hours and labs